# Path where RAW_GZ folder is located. Here all the outputs will be saved.
# For production on T2B -> data_path: "/pnfs/iihe/muraves/muraves_DATA/"
data_path: "/workspace/test" 
hodoscope:
  #- BLU
  - NERO

type:
  - ADC
  #- PIEDISTALLI
run:
  # A-B: execute from A to B
  2500-2509

  # A,B execute A and B
  #2500,2509
  
  # A: execute A
  #"11429"

